version: '3.4'

services:
  phantom-proxy:
    image: karl0ss/minecraftphantomproxydocker:latest
    container_name: minecraft-phantom
    environment:
      SERVER: example.com:19132
      ARM_VERSION: arm7
      #BIND_PORT: 0
      #BIND_IP: 0.0.0.0
      #TIMEOUT: 60
      #IPV6: 1
      #DEBUG: 1
      #REMOVE_PORTS: 1
      #WORKERS: 16
    network_mode: host
